dependencies: [equities_eod, corp_actions, delistings]
green_threshold: { window_years: 15, min_ratio: 0.98 }
cpcv: { folds: 8, embargo_days: 10 }
time_decay: { half_life_months: 18 }
regime_masks:
  - { name: 'pre-2012',  use_for: stress_only }
  - { name: '2012-2016', use_for: fit_and_validate }
  - { name: '2016-2024', use_for: fit_and_validate }
  - { name: '2025+',     use_for: monitor_only }
promotion_bars: { DSR_min: 0.0, PBO_max: 0.05, net_sharpe_min: 1.0 }
promotion_policy: { require_shadow_days: 20 }
