#!/usr/bin/env python
"""
Manual intraday pipeline smoke test (GPU/CPU) using curated-style fixtures.

This is intentionally separate from pytest/CI. It ingests the small fixtures
generated by ml_testing/build_intraday_fixture.py, runs the real intraday_xs
pipeline with shortened settings, and writes artifacts/reports under ml_testing/.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import List

from loguru import logger

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from models.intraday_xs import PatchConfig
from ops.pipelines.intraday_xs import IntradayConfig, run_intraday


def _parse_symbols(raw: str) -> List[str]:
    return [s.strip().upper() for s in raw.split(",") if s.strip()]


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Manual intraday pipeline smoke test (not wired to CI)")
    parser.add_argument("--start-date", default="2021-05-03", help="Inclusive start date (YYYY-MM-DD)")
    parser.add_argument("--end-date", default="2021-05-05", help="Inclusive end date (YYYY-MM-DD)")
    parser.add_argument("--universe", default="SPY", help="Comma-separated symbols (default: SPY)")
    parser.add_argument(
        "--minute-dir",
        default="ml_testing/fixtures/curated/equities_minute",
        help="Path to curated minute fixtures (date=YYYY-MM-DD/data.parquet)",
    )
    parser.add_argument(
        "--daily-dir",
        default="ml_testing/fixtures/curated/equities_ohlcv_adj",
        help="Path to curated daily bars for labeling",
    )
    parser.add_argument("--artifact-dir", default="ml_testing/artifacts/intraday_xs", help="Where to write artifacts")
    parser.add_argument("--report-dir", default="ml_testing/reports", help="Where to write daily report outputs")
    parser.add_argument("--min-train-samples", type=int, default=10, help="Minimum rows needed to train")
    parser.add_argument("--n-splits", type=int, default=2, help="CPCV train splits (kept small for speed)")
    parser.add_argument("--n-test-splits", type=int, default=1, help="CPCV test splits")
    parser.add_argument("--embargo-days", type=int, default=1, help="CPCV embargo days")
    parser.add_argument("--purge-days", type=int, default=1, help="CPCV purge days")
    parser.add_argument("--epochs", type=int, default=2, help="PatchTST epochs (torch backend)")
    parser.add_argument("--batch-size", type=int, default=32, help="PatchTST batch size (torch backend)")
    parser.add_argument("--context-length", type=int, default=64, help="PatchTST context length")
    parser.add_argument("--d-model", type=int, default=32, help="PatchTST hidden size")
    parser.add_argument("--dropout", type=float, default=0.1, help="PatchTST dropout")
    parser.add_argument("--lr", type=float, default=1e-3, help="PatchTST learning rate")
    return parser.parse_args()


def main() -> None:
    args = _parse_args()

    symbols = _parse_symbols(args.universe)
    patch_cfg = PatchConfig(
        context_length=args.context_length,
        d_model=args.d_model,
        dropout=args.dropout,
        epochs=args.epochs,
        lr=args.lr,
        batch_size=args.batch_size,
    )

    cfg = IntradayConfig(
        start_date=args.start_date,
        end_date=args.end_date,
        universe=symbols,
        min_train_samples=args.min_train_samples,
        n_splits=args.n_splits,
        n_test_splits=args.n_test_splits,
        embargo_days=args.embargo_days,
        purge_days=args.purge_days,
        patch_config=patch_cfg,
        minute_data_dir=str(Path(args.minute_dir)),
        daily_data_dir=str(Path(args.daily_dir)),
        artifact_dir=str(Path(args.artifact_dir)),
        report_dir=str(Path(args.report_dir)),
    )

    logger.info("Starting intraday_xs smoke run (manual only, not CI)")
    logger.info(f"Date window: {cfg.start_date} → {cfg.end_date}, universe={cfg.universe}")
    logger.info(f"Minute dir: {cfg.minute_data_dir} | Daily dir: {cfg.daily_data_dir}")

    results = run_intraday(cfg)

    status = results.get("status")
    logger.info(f"Pipeline status: {status}")
    if status != "ok":
        logger.warning(f"Early exit reason: {results}")
        return

    metrics = results.get("training_metrics", {})
    logger.info(f"Training metrics: {metrics}")

    weights = results.get("weights")
    if weights is not None:
        logger.info(f"Generated {len(weights)} weight rows for {weights['date'].nunique()} day(s)")

    logger.info(f"Artifacts written under: {cfg.artifact_dir}")
    logger.info(f"Reports written under: {cfg.report_dir}")


if __name__ == "__main__":
    main()
