router:
  fallback: best_available
  weights:
    equities_xs: 0.6
    intraday_xs: 0.3
    options_vol: 0.1
  stacker:
    enabled: false
    metadata_path: models/meta/artifacts/latest/metadata.json
    linear_weights:
      equities_xs: 0.7
      intraday_xs: 0.2
      options_vol: 0.1
  rl_policy:
    enabled: false
    model_path: models/rl/artifacts/policy_cql.pkl
